# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

# DNS 服务器和建立连接时的 静态 Hosts, 仅在 dns.enhanced-mode 模式为 redir-host 生效
# 支持通配符域名 (例如: *.clash.dev, *.foo.*.example.com )
# 不使用通配符的域名优先级高于使用通配符的域名 (例如: foo.example.com > *.example.com > .example.com )
# 注意: +.foo.com 的效果等同于 .foo.com 和 foo.com
hosts:
# '*.clash.dev': 127.0.0.1
# '.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'

# DNS 服务器配置(可选；若不配置，程序内置的 DNS 服务会被关闭)
dns:
  enable: false
  listen: 0.0.0.0:53
  ipv6: true # 当此选项为 false 时, AAAA 请求将返回空

  # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip # 或 redir-host
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
  # use-hosts: true # 查询 hosts 并返回 IP 记录

  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  fake-ip-filter:
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    # === LAN ===
    - '*.lan'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === NTP Service ===
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'

    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'

    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'

    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'

    - 'time1.cloud.tencent.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## Baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'

  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  # fallback:
  #   - https://dns.google/dns-query

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果不在 fallback-filter.ipcidr 范围内，
  # Clash 总会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 国家选择
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 自动选择
    type: url-test
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 手动选择
    type: select
    use:
      - all
  - name: 国家选择
    type: select
    proxies:
      - 美国节点
      - 狮城节点
      - 香港节点
      - 其他国家
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - REJECT
      - DIRECT
  - name: 社交服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 谷歌服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 全球媒体
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: Emby视频
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 负载均衡
    type: load-balance
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 失败切换
    type: fallback
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 美国节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - us
  - name: 香港节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - hk
  - name: 狮城节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - sg
  - name: 其他国家
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - others

proxy-providers:
  us:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-us.yml"
    interval: 86400
    path: ./TopFreeProxies/provider-us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  hk:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-hk.yml"
    interval: 86400
    path: ./TopFreeProxies/provider-hk.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  sg:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-sg.yml"
    interval: 86400
    path: ./TopFreeProxies/provider-sg.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  others:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-others.yml"
    interval: 86400
    path: ./TopFreeProxies/provider-others.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  all:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-all.yml"
    interval: 86400
    path: ./TopFreeProxies/provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rule-providers: # rule-providers from Logyalsoldier/clash-rules and LM-Firefly/Rules
  Apple:
    type: http
    behavior: domain # https://github.com/Dreamacro/clash/issues/1165
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./TopFreeProxies/ruleset/apple.yaml
  iCloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./TopFreeProxies/ruleset/icloud.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/Microsoft.yaml"
    path: ./TopFreeProxies/ruleset/microsoft.yaml
    interval: 86400
  Google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./TopFreeProxies/ruleset/google.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/GlobalMedia.yaml"
    path: ./TopFreeProxies/ruleset/globalmedia.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./TopFreeProxies/ruleset/telegramcidr.yaml
    interval: 86400
  Twitter:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Twitter.yaml"
    path: ./TopFreeProxies/ruleset/twitter.yaml
    interval: 86400
  Private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./TopFreeProxies/ruleset/private.yaml
    interval: 86400
  Local-LAN:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/Special/Local-LAN.yaml"
    path: ./TopFreeProxies/ruleset/local-lan.yaml
    interval: 86400
  Proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./TopFreeProxies/ruleset/proxy.yaml
    interval: 86400
  Direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./TopFreeProxies/ruleset/direct.yaml
    interval: 86400
  Reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./TopFreeProxies/ruleset/reject.yaml
    interval: 86400

rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT

  - DOMAIN-SUFFIX,emby.wtf,Emby视频,no-resolve
  - DOMAIN-SUFFIX,bitwarden.net,DIRECT,no-resolve
  - DOMAIN-SUFFIX,bitwarden.com,DIRECT,no-resolve

  - RULE-SET,Local-LAN,DIRECT
  - RULE-SET,Apple,苹果服务
  - RULE-SET,iCloud,苹果服务
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,Google,谷歌服务
  - RULE-SET,Twitter,社交服务
  - RULE-SET,Telegram,社交服务
  - RULE-SET,GlobalMedia,全球媒体
  - RULE-SET,Proxy,节点选择
  - RULE-SET,Reject,REJECT
  - RULE-SET,Private,DIRECT

  - IP-CIDR,10.240.0.0/24,DIRECT,no-resolve

  - GEOIP,CN,DIRECT # GeoIP2 数据库 from Hackl0us/GeoIP2-CN
  - MATCH,漏网之鱼
